# Generated by Django 5.2.15 on 2026-06-07 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product', 'Товар'), ('service', 'Услуга')], default='product', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Штрих-код')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('active', 'Активно'), ('rejected', 'Отклонено'), ('archived', 'В архиве'), ('out_of_stock', 'Нет в наличии'), ('on_order', 'Под заказ')], default='draft', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У'), ('refurbished', 'Восстановленный')], default='new', max_length=20)),
                ('has_warranty', models.BooleanField(default=False)),
                ('warranty_text', models.CharField(blank=True, max_length=500)),
                ('return_policy', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('chat_clicks', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingCarCompat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aggregate', models.CharField(blank=True, max_length=100)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_compat', to='listings.listing')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carmake')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('is_video', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Очередь модерации',
                'verbose_name_plural': 'Очередь модерации',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20)),
                ('seller_reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
