# Generated by Django 5.2.15 on 2026-06-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='matched_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_requests', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
